portfoliosite/portfolio_music_player/urls.py
"""
    This file is used to direct portfolio_music_player urls to their appropriate views.
"""
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'music_player'

urlpatterns = [
    path('', views.player, name='player'),
    path('albums/', views.AlbumListView.as_view(), name='albums'),
    path('songs/', views.SongListView.as_view(), name='songs'),
    path('songs/download/<int:id>/<str:file_type>', views.download_song, name='download_song'),
    path('albums/download/<int:id>/<str:file_type>', views.download_album, name='download_album'),
]

urlpatterns = format_suffix_patterns(urlpatterns)


# Addition for using uploaded media as static files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfoliosite/portfoliosite/urls.py
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    path('markdownx/', include(markdownx)),
    path('admin/', admin.site.urls),
    path('music/', include('portfolio_music_player.urls')),
    path('', include('resume.urls')),
    path('writing/', include('writing.urls')),
]

portfoliosite/resume/urls.py
"""
    This file is used to direct resume urls to their appropriate views.
"""
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from . import views

app_name = 'resume'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects', views.projects, name='projects'), 
    path('resume', views.resume, name='resume'),
]
"""
    Variable used to direct various urls to their appropriate views. 
"""

# Addition for using uploaded media as static files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfoliosite/writing/urls.py
"""
    This file is used to direct writing urls to their appropriate views for writing app.
"""
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from . import views

app_name = 'writing'

urlpatterns = [
    path('', views.writing_landing, name='writing_landing'),
    path('category/<int:category_id>', views.writing_category, name='writing_category'),
    path('project/<int:project_id>', views.writing_project, name='writing_project'),
    path('topic_tag/<int:topic_tag_id>', views.writing_topic_tag, name='writing_topic_tag'),
    path('piece/<int:writing_id>', views.writing, name='piece'),
]
"""
    Variable used to direct various urls to their appropriate views. 
"""

# Addition for using uploaded media as static files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfoliosite/templates/base.html
{% comment "Overview" %}
    This is a base html file that can be used by templates which connects
    to bootsrap and any other necessary site-wide css, while creating a navigation bar
    and footer.

    The head-add block can be used to add things to the html head.

    The title block can be used to add a page title. Default is "Micah Huff's Site."

    The main-content block can be used to add content to the center of the page, between the
    navigation and the footer
{% endcomment %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/core.css' %}" rel="stylesheet" >

    {% block head-add %}
    {% endblock %}


    <title>{% block title %} Micah Huff's Site {% endblock %}</title>
  </head>
  <body class="d-flex flex-column min-vh-100 text-white bg-primary">
    
    {% include "main_menu.html" %}

    {% block main-content %}
    {% endblock %}

    <!-- ******************Footer******************** -->
    <footer class="footer mt-auto py-2 bg-dark">
            <img src="{% static 'img/sitelogo.png' %}" alt="logo" class="mx-auto d-block"/>
    </footer>
    <!-- ******************End Footer******************** -->

    <!-- ********Script Linking ****************** -->
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

  </body>
</html>

portfoliosite/templates/main_menu.html
{% load static %}
{% load version %}
<!-- ***********Navbar************* -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <a class="navbar-brand d-md-none" href="{% url 'resume:index' %}">
        <img src="{% static 'img/sitelogo.png' %}" alt="logo"/>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerTarget" aria-controls="navbarTogglerTarget" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerTarget">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
            <li class="nav-item h4 pe-4 ps-4">
            {% url 'resume:index' as index %}
            <a class="nav-link {% if request.path == index %}active{% endif %}" aria-current="page" href="{{ index }}">Home</a>
            </li>
            <li class="nav-item h4 pe-4 ps-4">
            {% url 'resume:resume' as resume %}
            <a class="nav-link {% if request.path == resume %}active{% endif %}" href="{{ resume }}">Resume</a>
            </li>
            <li class="nav-item d-none d-md-block pe-4 ps-4">
            <a class="nav-link" href="{% url 'resume:index' %}">
                <img src="{% static 'img/sitelogo.png' %}" alt="logo"/>
            </a>
            </li>
            <li class="nav-item h4 pe-4 ps-4">
            {% url 'music_player:player' as music_player %}
            <a class="nav-link" href="{% url 'music_player:player' %}">Music</a>
            </li>
            <li class="nav-item h4 pe-4 ps-4">
            {% url 'writing:writing_landing' as writing %}
            <a class="nav-link {% if request.path == writing %}active{% endif %}" href="{{ writing }}">Writing</a>
            </li>
        </ul>
        </div>

    </div>
</nav>
<!-- **************** End of Navbar ************************** -->